
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvqyyjyzwqpgirsqxjei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cXl5anl6d3FwZ2lyc3F4amVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTI1OTQsImV4cCI6MjA2NjU4ODU5NH0.IE-VSmH98FTYUCeDOnJvG1BwK-xk3dOh1eAtWbMAFdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
  global: {
    headers: {
      'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
    },
  },
});

// Function to set Clerk token for Supabase auth
export const setSupabaseAuth = (token: string | null) => {
  if (token) {
    supabase.auth.setSession({
      access_token: token,
      refresh_token: '',
      user: null as any,
      token_type: 'bearer',
      expires_in: 3600,
      expires_at: Math.floor(Date.now() / 1000) + 3600
    });
  }
};
